name: Build Executables

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller scapy
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libpcap-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install libpcap
        fi
        
    - name: Build executable
      run: |
        pyinstaller --onefile --hidden-import=scapy --hidden-import=scapy.all --hidden-import=scapy.arch main.py
        mv dist/main dist/main-${{ runner.os }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: dist/
